# =============================
# Daniel Elmore — Portfolio Site
# Minimal Mistakes Jekyll config
# =============================

# ---------------------------------
# Theme Settings
# ---------------------------------
# Use a built-in skin for quick styling tweaks. You can change this later to
# "air", "mint", "plum", etc.
minimal_mistakes_skin: "default"
remote_theme: "mmistakes/minimal-mistakes"

# ---------------------------------
# Site Settings
# ---------------------------------
locale: "en-US"
rtl:     # true/false; keep empty for LTR

# Masthead & metadata
title: "Daniel Elmore Portfolio"
title_separator: "-"
subtitle: "Data Analysis, Economics, and Strategy Projects"
name: "Daniel Elmore"
description: "Data & Strategy Consultant | Economics Graduate Student"

# URLs
url: "https://daniel-elmore.github.io"   # production URL
baseurl: ""                               # root site (no subpath)
repository: "Daniel-Elmore/Daniel-Elmore.github.io"

# Branding assets (optional)
teaser:                 # e.g., "/assets/images/500x300.png"
logo:                   # e.g., "/assets/images/logo.png"
masthead_title: " "     # single space hides duplicate title in masthead

# UX
breadcrumbs:            # true/false
words_per_minute: 200
enable_copy_code_button: true

# Legal
copyright: "Daniel Elmore"
copyright_url: "https://daniel-elmore.github.io"

# Comments (disabled by default for a portfolio)
comments:
  provider:

# reCaptcha (unused)
reCaptcha:
  siteKey:
  secret:

# Feeds & Search
atom_feed:
  path:                  # default feed.xml
  hide:
search:                  # default false shows search icon when enabled by skin
search_full_content:
search_provider: lunr
lunr:
  search_within_pages:

# SEO verification (optional)
google_site_verification:
bing_site_verification:
naver_site_verification:
yandex_site_verification:
baidu_site_verification:

# ---------------------------------
# Social Sharing / Profiles
# ---------------------------------
# Set Open Graph default image if you have one.
og_image:               # e.g., "/assets/images/og-image.png"

social:
  type: Person
  name: "Daniel Elmore"
  links:
    - "https://www.linkedin.com/in/daniel-elmore/"
    - "https://github.com/Daniel-Elmore"

# ---------------------------------
# Analytics (disabled)
# ---------------------------------
analytics:
  provider: false
  google:
    tracking_id:
    anonymize_ip:

# ---------------------------------
# Site Author (appears in sidebar on layouts with author_profile: true)
# ---------------------------------
author:
  name: "Daniel Elmore"
  avatar:               # e.g., "/assets/images/daniel.jpg"
  bio: "Data & Strategy Consultant and Economics Graduate Student. I use SQL, Python, and econometrics to connect economic reasoning with business strategy."
  location: "Taylorsville, NC"
  email: "danieljosephelmore@gmail.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:danieljosephelmore@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/daniel-elmore/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Daniel-Elmore"

# ---------------------------------
# Footer Links
# ---------------------------------
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/daniel-elmore/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Daniel-Elmore"
  since: "2025"

# ---------------------------------
# Reading / Build Settings
# ---------------------------------
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - minimal-mistakes-jekyll.gemspec
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# ---------------------------------
# Conversion
# ---------------------------------
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# ---------------------------------
# Outputting
# ---------------------------------
permalink: /:title/
timezone: "America/New_York"

# ---------------------------------
# Pagination (disabled for portfolio)
# ---------------------------------

# Disable advanced pagination (jekyll-paginate-v2)
pagination:
  enabled: false

# ---------------------------------
# Plugins (GitHub Pages–compatible)
# ---------------------------------
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe (whitelist must match plugins above)
whitelist:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

# ---------------------------------
# Archives (no pages rendered unless you add archive pages)
# ---------------------------------
category_archive:
  type: liquid
  path:
tag_archive:
  type: liquid
  path:

# ---------------------------------
# HTML Compression
# ---------------------------------
compress_html:
  clippings: all
  ignore:
    envs: development

# ---------------------------------
# Collections (Projects)
# ---------------------------------
collections:
  projects:
    output: true
    permalink: /projects/:name/

# ---------------------------------
# Defaults
# ---------------------------------
defaults:
  # _posts (keep even if you’re not blogging yet)
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments:
      share: true
      related: true

  # _projects (ensure project pages render with sidebar)
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      share: false
      related: false
